name: CI-CD-Pipeline-to_AWS-ELasticBeastalk
env:
 EB_PACKAGE_S3_BUCKET_NAME : "adv-it-flask-application-packagest"
 EB_APPLICATION_NAME       : "MyFlask"
 EB_ENVIRONMENT_NAME       : "MyFlask-env"
 AWS_REGION_NAME           : "us-west-2"
 DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
 
 
on:
  push:
    branches: [ "master" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    
    steps:
      - name: Git clone our repo
      - uses: actions/checkout@v1
      
      - name: create zip deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *git*
